# Generated by Django 4.2.3 on 2023-08-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Connection State',
                'verbose_name_plural': 'Connection States',
            },
        ),
        migrations.CreateModel(
            name='FWActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Firewall Action',
                'verbose_name_plural': 'Firewall Actions',
            },
        ),
        migrations.CreateModel(
            name='FWInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Firewall Interface',
                'verbose_name_plural': 'Firewall Interfaces',
            },
        ),
        migrations.CreateModel(
            name='FWNameRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.fwactions')),
            ],
            options={
                'verbose_name': 'Firewall Named Rule',
                'verbose_name_plural': 'Firewall Named Rules',
            },
        ),
        migrations.CreateModel(
            name='FWZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('interfaces', models.ManyToManyField(blank=True, to='generator.fwinterface')),
            ],
            options={
                'verbose_name': 'Firewall Zone',
                'verbose_name_plural': 'Firewall Zones',
            },
        ),
        migrations.CreateModel(
            name='IPProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'IP Protocol',
                'verbose_name_plural': 'IP Protocols',
            },
        ),
        migrations.CreateModel(
            name='FWZoneMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_zone', to='generator.fwzone')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.fwnamerule')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_zone', to='generator.fwzone')),
            ],
            options={
                'verbose_name': 'Firewall From Zone Mapping',
                'verbose_name_plural': 'Firewall From Zone Mappings',
            },
        ),
        migrations.AddField(
            model_name='fwzone',
            name='zone_map',
            field=models.ManyToManyField(through='generator.FWZoneMap', to='generator.fwzone'),
        ),
        migrations.CreateModel(
            name='FWRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.IntegerField()),
                ('src_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.fwactions')),
                ('conn_status', models.ManyToManyField(blank=True, to='generator.connstate')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.ipprotocol')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.fwnamerule')),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
            },
        ),
    ]
