# Generated by Django 4.2.3 on 2023-07-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_fwzone_from_zone_fwzone_zone_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fwzone',
            name='interfaces',
        ),
        migrations.AddField(
            model_name='fwinterface',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.fwzone'),
            preserve_default=False,
        ),
    ]
