# Generated by Django 4.2.3 on 2023-07-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_fwzone_interfaces_fwinterface_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fwinterface',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='generator.fwzone'),
        ),
    ]
