# Generated by Django 4.2.3 on 2023-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_fwinterface_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fwinterface',
            name='zone',
        ),
        migrations.AddField(
            model_name='fwzone',
            name='interfaces',
            field=models.ManyToManyField(blank=True, to='generator.fwinterface'),
        ),
    ]
